[project]
name = "syfu"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.14"
dependencies = [
    "chromadb>=1.5.9",
    "fastapi[standard]>=0.139.0",
    "ipykernel>=7.3.0",
    "langchain>=1.3.14",
    "langchain-chroma>=1.1.0",
    "langchain-community>=0.4.2",
    "langchain-core>=1.4.9",
    "langchain-experimental>=0.4.2",
    "langchain-google-genai>=4.2.7",
    "langchain-groq>=1.1.3",
    "langchain-nvidia-ai-endpoints>=1.4.3",
    "langchain-ollama>=1.1.0",
    "langchain-openai>=1.3.5",
    "langchain-text-splitters>=1.1.2",
    "langchain-unstructured[local]>=1.0.1",
    "langgraph>=1.2.9",
    "pydantic>=2.13.4",
    "pypdf>=6.14.2",
    "python-dotenv>=1.2.2",
    "sqlalchemy>=2.0.51",
]

[build-system]
requires = ["hatchling"]
build-backend = "hatchling.build"

[tool.hatch.build.targets.wheel]
packages = ["src/syfu"]

[tool.basedpyright]
# Lower the strictness level: "basic", "standard", "recommended", or "strict"
typeCheckingMode = "basic"

# Or disable the specific rules seen in your editor:
reportMissingTypeStubs = false       # Fixes "Stub file not found for 'syfu...'"
reportMissingTypeArgument = false    # Fixes "Expected type arguments for generic class 'dict'"
